name: Review
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spelling:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
          locale: "US"
